services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: api
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: lockers
    ports:
      - 5432:5432

  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 3000:3000
