@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

GET http://{{host}}/rents

###

GET http://{{host}}/rents/50be06a8-1dec-4b18-a23c-e98588207752

###

POST http://{{host}}/rents
Content-Type: application/json

{
  "size": "M",
  "status": "CREATED",
  "weight": 5,
  "lockerId": "1b8d1e89-2514-4d91-b813-044bf0ce8d20"
}

###

PUT http://{{host}}/rents/ec9e44fa-f93d-43ef-8a75-089d46496f50
Content-Type: application/json

{
  "status": "WAITING_DROPOFF"
}

###

DELETE http://{{host}}/rents/50be06a8-1dec-4b18-a23c-e98588207752
