@hostname = localhost
@port = 3000
@host = {{hostname}}:{{port}}

# Prepare Rent
# Will allocate a Locker for the new Rent
POST http://{{host}}/prepare-rent
Content-Type: application/json

{
  "lockerId": "8b4b59ae-8de5-4322-a426-79c29315a9f1",
  "weight": 5,
  "size": "M"
}
